apiVersion: v1
kind: Service
metadata:
  labels:
    app: default-application
  name: default-application
spec:
  type: NodePort
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  selector:
    app: default-application
